import type { Metadata } from "next";
import AdminResumesView from "@/src/components/dashboard/admin/AdminResumesView/AdminResumesView";

export const metadata: Metadata = {
  title: "Learner Resumes",
  description: "Review ATS optimization scores, keywords, and AI resumes generated by learners.",
};

export default function Page() {
  return <AdminResumesView />;
}
